import Head from "next/head";
import { BsFillMoonStarsFill, BsFillTelephoneFill } from "react-icons/bs";
import { MdEmail, MdLocationPin } from "react-icons/md";
import {
  AiFillLinkedin,
  AiFillFacebook,
  AiFillInstagram,
  AiFillGithub,
  AiOutlineCloudDownload,
  AiFillHtml5,
} from "react-icons/ai";
import { DiCss3, DiMysql, DiSass } from "react-icons/di";
import {
  SiTailwindcss,
  SiJavascript,
  SiReact,
  SiPhp,
  SiFigma,
  SiAdobephotoshop,
  SiNextdotjs,
} from "react-icons/si";
import Image from "next/image";
import laki from "../public/laki.png";
import mwmockup from "../public/mwmockup.png";
import ebankmockup from "../public/ebankmockup.png";
import stopwatchmockup from "../public/stopwatchmockup.png";
import spinmockup from "../public/spinmockup.png";
import animmockup from "../public/animmockup.png";
import reflexmockup from "../public/reflexmockup.png";
import calcmockup from "../public/calcmockup.png";
import { useState } from "react";

const goToProject = () => {
  const projects = document.getElementById("projects");
  projects.scrollIntoView({ behavior: "smooth" });
};

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Panovic Lazar Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" px-6 font-quicksand dark:bg-gray-900">
        <section className="min-h-screen py-10">
          <nav className=" flex justify-between mb-10 pr-4">
            <h1 className=" text-2xl dark:text-white">lakidev</h1>
            <ul className=" flex gap-10 items-center">
              <li className=" text-2xl cursor-pointer">
                <BsFillMoonStarsFill
                  className="dark:text-yellow-400"
                  onClick={() => setDarkMode(!darkMode)}
                ></BsFillMoonStarsFill>
              </li>
              {/* <li className=" bg-gradient-to-r from-blue-700 to-cyan-500 text-white px-5 py-2 rounded-md">
                Resume
              </li> */}
            </ul>
          </nav>
          <div className=" text-center p-10">
            <p className=" text-4xl text-cyan-500 font-quicksandbold py-2 md:text-6xl">
              Panović Lazar
            </p>
            <p className=" py-2 text-2xl md:text-3xl dark:text-white">
              Front-End Web Developer
            </p>
            <p className=" font-quicksand text-lg py-5 leading-8 text-gray-700 md:text-2xl max-w-xl mx-auto dark:text-gray-400">
              Self-taught web developer who provides web programming services,
              with a focus on front end web development. Scroll down below for
              more information
            </p>
          </div>
          <div className=" text-gray-700 mb-14 flex justify-around text-7xl dark:text-yellow-400">
            <a
              href="https://www.facebook.com/lazar.panovic"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillFacebook></AiFillFacebook>
            </a>
            <a
              href="https://www.linkedin.com/in/lazar-panovi%C4%87-252160209/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillLinkedin></AiFillLinkedin>
            </a>
            <a
              href="https://www.instagram.com/lazarpanovic/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillInstagram></AiFillInstagram>
            </a>
            <a
              href="https://github.com/Panoviclazar/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillGithub></AiFillGithub>
            </a>
          </div>
          <div className="relative bg-gradient-to-br from-cyan-400 w-60 h-60 mx-auto rounded-full overflow-hidden md:w-96 md:h-96 dark:to-white">
            <Image src={laki} alt="developer"></Image>
          </div>
        </section>
        <section className="mt-6">
          <div className="mb-10">
            <h1 className="text-left text-3xl font-quicksandbold mb-10 dark:text-white">
              What am I do?
            </h1>
            <p className="text-gray-500 text-left leading-7 text-lg lg:pr-20 dark:text-gray-400">
              More than a year ago, my programming journey started, like every
              web developer, I started with{" "}
              <span className="text-green-500">HTML</span> and simple websites
              and thanks to a lot of effort and days and nights spent on the
              computer, I reached <span className="text-blue-600">ReactJS</span>{" "}
              and cool web apps. In short, I love React and its frameworks, as
              well as all the possibilities it provides on the client side.
              Although this is just my beginning with React, I believe that with
              a lot of effort and a suitable environment, I will progress
              quickly and be ready for big projects. It is my dream, like every
              programmers, to one day be a{" "}
              <span className="text-red-500">Full Stack Web Developer</span>.
            </p>
          </div>
          <div className=" font-quicksand">
            <h1 className="text-left text-3xl font-quicksandbold mt-14 mb-10 dark:text-white">
              What am I use?
            </h1>
          </div>
          <div className="lg:grid lg:grid-cols-3">
            <div className="px-4 bg-gradient-to-br from-cyan-800 to-cyan-500 py-6 text-xl mt-14 mb-4 w-48 mx-auto shadow-xl rounded-3xl flex-column border-1 text-white">
              <p className="text-center pb-4 border-b text-3xl italic">
                Structure
              </p>
              <AiFillHtml5 className=" mx-auto text-5xl mt-4 mb-2"></AiFillHtml5>
              <p className=" text-center font-quicksandbold">HTML5</p>
            </div>
            <div className="px-4 bg-gradient-to-br from-cyan-800 to-cyan-500 text-white py-6 text-xl mt-10 mb-4 mx-auto shadow-xl rounded-3xl flex-column border-1">
              <p className=" pb-4 italic text-center border-b text-3xl">
                Style
              </p>
              <div className="flex justify-around md:gap-4">
                <div>
                  <DiCss3 className=" text-5xl mt-4 mb-2"></DiCss3>
                  <p className=" font-quicksandbold text-center">CSS3</p>
                </div>
                <div>
                  <DiSass className=" text-5xl mt-4 mb-2"></DiSass>
                  <p className=" font-quicksandbold text-center">SASS</p>
                </div>
                <div>
                  <SiTailwindcss className=" mx-auto text-5xl mt-4 mb-2"></SiTailwindcss>
                  <p className=" font-quicksandbold text-center">Tailwind</p>
                </div>
              </div>
            </div>
            <div className="px-4 bg-gradient-to-br from-cyan-800 to-cyan-500 text-white py-6 text-xl mt-10 mb-4 mx-auto shadow-xl rounded-3xl flex-column border-1">
              <p className=" pb-4 italic text-center border-b text-3xl">
                App Functionality
              </p>
              <div className="flex justify-around md:gap-4">
                <div>
                  <SiJavascript className=" text-5xl mt-4 mb-2 mx-auto"></SiJavascript>
                  <p className=" font-quicksandbold text-center">VanilaJS</p>
                </div>
                <div>
                  <SiReact className=" text-5xl mt-4 mb-2 mx-auto"></SiReact>
                  <p className=" font-quicksandbold text-center">ReactJS</p>
                </div>
                <div>
                  <SiNextdotjs className=" mx-auto text-5xl mt-4 mb-2"></SiNextdotjs>
                  <p className=" font-quicksandbold text-center">NextJS</p>
                </div>
              </div>
            </div>
            <div className="px-4 bg-gradient-to-br from-cyan-800 to-cyan-500 text-white py-6 text-xl mt-10 mb-4 mx-auto shadow-xl rounded-3xl flex-column border-1">
              <p className=" pb-4 italic text-center border-b text-3xl">
                Back-end
              </p>
              <div className="flex justify-around">
                <div>
                  <SiPhp className=" text-5xl mt-4 mb-2"></SiPhp>
                  <p className=" font-quicksandbold text-center">PHP</p>
                </div>
                <div>
                  <DiMysql className=" text-5xl mt-4 mb-2 mx-auto"></DiMysql>
                  <p className=" font-quicksandbold text-center">MySQL</p>
                </div>
              </div>
            </div>
            <div className="px-4 bg-gradient-to-br from-cyan-800 to-cyan-500 text-white py-6 text-xl mt-10 mb-4 mx-auto shadow-xl rounded-3xl flex-column border-1">
              <p className=" pb-4 italic text-center border-b text-3xl">
                Design
              </p>
              <div className="flex justify-around md:gap-4">
                <div>
                  <SiFigma className=" text-5xl mt-4 mb-2"></SiFigma>
                  <p className=" font-quicksandbold text-center">Figma</p>
                </div>
                <div>
                  <SiAdobephotoshop className=" text-5xl mt-4 mb-2 mx-auto"></SiAdobephotoshop>
                  <p className=" font-quicksandbold text-center">Photoshop</p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="mt-20">
          <div className="mb-10 grid">
            <h1 className="text-left text-3xl font-quicksandbold mb-10 dark:text-white">
              My work
            </h1>
            <p className="text-gray-500 text-left leading-7 text-lg lg:pr-20 dark:text-gray-400">
              I have done remote work as a freelancer. I mostly build websites
              and smaller apps. I did the entire design of the websites, as well
              as the design and functionality of the applications, completely by
              myself, so far I have not had the opportunity to work with other
              colleagues. My primary job is{" "}
              <span className=" text-blue-600">front-end web developing</span>,
              but I also partially know back-end web developing, such as
              different types of contact forms or working with sql databases.
            </p>
            <button
              className="mt-20 px-14 py-2 w-52 mx-auto text-cyan-800 border-cyan-800 border shadow-xl text-2xl active:scale-90 hover:bg-cyan-500 hover:text-white hover:translate-y-2 transition duration-500 dark:bg-cyan-500 dark:text-white dark:hover:bg-transparent"
              onClick={goToProject}
            >
              Projects
            </button>
          </div>
          <div className="lg:grid grid-cols-3 gap-10">
            <a
              href="https://mw-concept.net/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <div className=" mt-28 lg:mt-20" id="projects">
                <p className="text-center text-3xl font-quicksandlight dark:text-white">
                  mw concept
                </p>
                <div className=" mt-4 shadow-2xl rounded-xl dark:bg-white dark:bg-opacity-60 hover:dark:bg-opacity-80 dark:hover:scale-110">
                  <Image src={mwmockup} alt="mw-concept"></Image>
                </div>
              </div>
            </a>
            <a
              href="https://lazar-ebanking.netlify.app/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <div className=" mt-20">
                <p className="text-center text-3xl font-quicksandlight dark:text-white">
                  modern e-banking
                </p>
                <div className=" mt-4 shadow-2xl rounded-xl dark:bg-white dark:bg-opacity-60 hover:dark:bg-opacity-80 dark:hover:scale-110">
                  <Image src={ebankmockup} alt="e-banking"></Image>
                </div>
              </div>
            </a>
            <a
              href="https://laki-stopwatch-game.netlify.app/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <div className=" mt-20">
                <p className="text-center text-3xl font-quicksandlight dark:text-white">
                  stopwatch game
                </p>
                <div className=" mt-4 shadow-2xl rounded-xl dark:bg-white dark:bg-opacity-60 hover:dark:bg-opacity-80 dark:hover:scale-110">
                  <Image src={stopwatchmockup} alt="stopwatch"></Image>
                </div>
              </div>
            </a>
            <a
              href="https://laki-spin.netlify.app/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <div className=" mt-20">
                <p className="text-center text-3xl font-quicksandlight dark:text-white">
                  lucky spin
                </p>
                <div className=" mt-4 shadow-2xl rounded-xl dark:bg-white dark:bg-opacity-60 hover:dark:bg-opacity-80 dark:hover:scale-110">
                  <Image src={spinmockup} alt="lucky-spin"></Image>
                </div>
              </div>
            </a>
            <a
              href="https://laki-3d-animation.netlify.app/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <div className=" mt-20">
                <p className="text-center text-3xl font-quicksandlight dark:text-white">
                  3d animation
                </p>
                <div className=" mt-4 shadow-2xl rounded-xl dark:bg-white dark:bg-opacity-60 hover:dark:bg-opacity-80 dark:hover:scale-110">
                  <Image src={animmockup} alt="animation"></Image>
                </div>
              </div>
            </a>
            <a
              href="https://laki-reflex-game.netlify.app/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <div className=" mt-20">
                <p className="text-center text-3xl font-quicksandlight dark:text-white">
                  reflex game
                </p>
                <div className=" mt-4 shadow-2xl rounded-xl dark:bg-white dark:bg-opacity-60 hover:dark:bg-opacity-80 dark:hover:scale-110">
                  <Image src={reflexmockup} alt="reflex"></Image>
                </div>
              </div>
            </a>
            <a
              href="https://laki-calculator.netlify.app/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <div className=" mt-20">
                <p className="text-center text-3xl font-quicksandlight dark:text-white">
                  simple calculator
                </p>
                <div className=" mt-4 shadow-2xl rounded-xl dark:bg-white dark:bg-opacity-60 hover:dark:bg-opacity-80 dark:hover:scale-110">
                  <Image src={calcmockup} alt="calculator"></Image>
                </div>
              </div>
            </a>
          </div>
        </section>
        <section className="mt-20">
          <h1 className="text-left text-3xl font-quicksandbold mb-10 dark:text-white">
            Contact
          </h1>
          <p className="text-gray-500 text-left leading-7 text-lg lg:pr-20 dark:text-gray-400">
            If you liked my way of working and my projects, feel free to contact
            me. I am available for any type of cooperation, whether it is some
            type of consulting or help with your work, as well as for any type
            of employment, both full-time and part-time or in the form of
            freelance. Of course, any suggestion, whether positive or negative,
            is welcome, because any feedback on our work means a lot to us
            developers, and it gives us room to improve our work.
          </p>
          <div className="mt-20 lg:flex justify-around items-center">
            <div>
              <div className="flex items-center gap-4">
                <a href="tel:+38163-260-213">
                  <BsFillTelephoneFill className="text-5xl text-cyan-500 dark:text-yellow-400"></BsFillTelephoneFill>
                </a>
                <p className=" text-xl text-gray-500 dark:text-gray-400">
                  +381 63 260 213
                </p>
              </div>
              <div className="flex items-center gap-4 mt-10 lg:mt-20">
                <a href="mailto:lazarpanovic@yahoo.com">
                  <MdEmail className="text-5xl text-cyan-500 dark:text-yellow-400"></MdEmail>
                </a>
                <p className=" text-xl text-gray-500 dark:text-gray-400">
                  lazarpanovic@yahoo.com
                </p>
              </div>
              <div className="flex items-center gap-4 mt-10 lg:mt-20">
                <a
                  target="_blank"
                  href="https://goo.gl/maps/F5rMUK1WhLjqEv8K6"
                  rel="noopener noreferrer"
                >
                  <MdLocationPin className="text-5xl text-cyan-500 dark:text-yellow-400"></MdLocationPin>
                </a>
                <p className=" text-xl text-gray-500 dark:text-gray-400">
                  Požega, Serbia
                </p>
              </div>
              <div className="flex items-center gap-4 mt-10 lg:mt-20">
                <a
                  target="_blank"
                  href="https://files.fm/u/nycuhfej3#/view/4caq7ghsf"
                  rel="noopener noreferrer"
                >
                  <AiOutlineCloudDownload className="text-5xl text-cyan-500 dark:text-yellow-400"></AiOutlineCloudDownload>
                </a>
                <p className=" text-xl text-gray-500 dark:text-gray-400">
                  Resume
                </p>
              </div>
            </div>
            <div className=" hidden lg:block w-1 h-[500px] border-r border-cyan-400 dark:border-white"></div>
            <form
              action="../contactform.php"
              method="post"
              className=" mt-14 grid gap-10 lg:w-80 lg:mt-0 pb-20"
            >
              <input
                className=" transition text-center text-2xl border-b border-cyan-400 focus:outline-none outline-none focus:placeholder:-translate-x-16 text-gray-500 dark:bg-transparent dark:border-b-gray-400"
                type="text"
                name="firstName"
                id=""
                placeholder="First name"
              />
              <input
                className="text-center text-2xl border-b border-cyan-400 focus:outline-none outline-none focus:placeholder:-translate-x-16 text-gray-500 dark:bg-transparent dark:border-b-gray-400"
                type="text"
                name="lastName"
                id=""
                placeholder="Last name"
              />
              <input
                className="text-center text-2xl border-b border-cyan-400 focus:outline-none outline-none focus:placeholder:-translate-x-16 text-gray-500 dark:bg-transparent dark:border-b-gray-400"
                type="email"
                name="email"
                id=""
                placeholder="Your Email"
              />
              <input
                className="text-center text-2xl border-b border-cyan-400 focus:outline-none outline-none focus:placeholder:-translate-x-16 text-gray-500 dark:bg-transparent dark:border-b-gray-400"
                type="number"
                name="number"
                id=""
                placeholder="Your Phone"
              />
              <p className="text-center text-gray-400 text-2xl">Your Message</p>
              <textarea
                name="message"
                id=""
                cols="30"
                rows="10"
                className="border-cyan-400 -mt-10 border appearance-none outline-none focus:outline-none rounded-xl p-6 text-gray-500 h-52 text-xl dark:bg-transparent dark:border-gray-400"
              ></textarea>
              <button
                name="send"
                className=" bg-gradient-to-br from-teal-700 to-cyan-400 w-40 py-2 text-white mx-auto text-lg lg:text-2xl active:scale-90 hover:bg-cyan-500 hover:text-white dark:transition dark:duration-500 dark:bg-cyan-500 dark:text-white dark:hover:bg-transparent border border-cyan-400 dark:from-teal-400 dark:to-teal-400 dark:hover:from-transparent dark:hover:to-transparent dark:hover:border dark:hover:border-teal-400"
              >
                Send
              </button>
            </form>
          </div>
        </section>
      </main>
      <footer className="mt-0 bg-gradient-to-br from-teal-800 to-cyan-500 pt-32 p-2 font-quicksand text-white dark:bg-gradient-to-b dark:from-gray-900 dark:to-gray-800">
        <h1 className=" text-7xl">Thanks</h1>
      </footer>
    </div>
  );
}
